name: 'ssh-deploy-nodejs'
description: 'Deploying a Node.js Project on a Remote Server via SSH'
author: 'lycpan233'

branding:
  icon: 'heart'
  color: 'purple'

inputs:
  host:
    description: 'IP address of the host'
    required: true
  username:
    description: 'Username of SSH user'
    required: true
  port:
    description: 'Port of SSH Protocol'
    required: false
    default: '22'
  password:
    description: 'Password of user, if not using private key'
    required: false
  privateKey:
    description: 'Private Key of user, if not using password'
    required: false
  workdir:
    description: 'Specify working directory'
    required: false
  source:
    description: 'Source path of the file to be uploadeds'
    required: false
  destination:
    description: 'The destination path of the remote'
    required: false
  scripts:
    description: 'Shell command to be executed'
    required: false

outputs:
  status:
    description: 'Execution Status of the Action'

runs:
  using: node20
  main: dist/index.js
