name: 'ssh-deploy-nodejs'
description: 'Deploying a Node.js Project on a Remote Server via SSH'
author: 'lycpan233'

branding:
  icon: 'heart'
  color: 'purple'


inputs:
  host:
    description: 'IP address of the host'
    required: true
  port:
    description: 'Port of SSH Protocol'
    required: false
    default: "22"
  username:
    description: 'Username of SSH user'
    required: true
  password:
    description: 'Password of user, if not using private key'
    required: false
  privateKey:
    description: 'Private Key of user, if not using password'
    required: false
  scripts:
    description: 'Shell command to be executed'
    required: false

outputs:
  time:
    description: 'Your output description here'

runs:
  using: node20
  main: dist/index.js
